name: 'GSA/grace-sqs-poc'
description: 'Proof-of-Concept for provisioning via Amazaon SQS'
license: null
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
contact:
    email: devsecops-core@gsa.gov
